# IP assignments for K-Social services
export APP_K_SOCIAL_WEB_ADDRESS="10.21.24.20"
export APP_K_SOCIAL_KWEBSERVER_ADDRESS="10.21.24.21"
export APP_K_SOCIAL_PROCESSOR_ADDRESS="10.21.24.22"

export APP_K_SOCIAL_PORT="8090"
export APP_K_SOCIAL_KWEBSERVER_PORT="8081"
export APP_K_SOCIAL_KWEBSERVER_API_URI="http://${APP_K_SOCIAL_KWEBSERVER_ADDRESS}:${APP_K_SOCIAL_KWEBSERVER_PORT}"
